### ISSUE TITLE
Ability to change order

### ISSUE THREAD

**Issue by ryan-sf** [gmlewis/flutter-stylizer#11]
I would like the ability to configure the order of flutter-stylizer.

**Comment by gmlewis** [comment]
Can you please give me an example of how you might envision this configuration and I'll see what I can do. Thank you!

**Comment by chimon2000** [comment]
I envision it working similar to tslint's [member-ordering](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/member-ordering.md) or vue's [attribute-order](https://eslint.vuejs.org/rules/attributes-order.html) rules.

Here are the rules that I came up with:

```
{
  "member-ordering": [
    "public-constructor",
    "private-constructor",
    "named-constructor",
    "factory-constructor",
    "public-static-field",
    "private-static-field",
    "public-instance-field",
    "private-instance-field",
    "public-static-method",
    "private-static-method",
    "public-instance-method",
    "private-instance-method",
    "public-override-method",
    "public-abstract-method",
    "build-method"
  ]
}
```

**Comment by gmlewis** [comment]
As I'm working on this issue and going through the code, Flutter Stylizer currently only has the
following concepts:

```
{
  "flutterStylizer.memberOrdering": {
    "type": "array",
    "default": [
      "public-constructor",
      "named-constructors",
      "public-static-variables",
      "public-instance-variables",
      "private-static-variables",
      "private-instance-variables",
      "public-override-methods",
      "public-other-methods",
      "build-method"
    ],
    "description": "Ordered list of members to control reordering of source code."
  }
}
```

so this is how I'm proceeding.  If further distinctions are desired like shown above, they would each have to be addressed in a new issue.

In other words, we'll get the configuration working first, then address requests for further classifications in future issues and updates.

**Comment by chimon2000** [comment]
Love it!
