### ISSUE TITLE
extract to standalone library

### ISSUE THREAD

**Issue by themightychris** [gmlewis/flutter-stylizer#13]
Thanks for this great work! I'd like to have a GitHub action apply these formatting policies automatically to every PR.

How difficult would it be to make a standalone tool that could be run from a command line to apply this formatting to arbitrary files on disk? The discussion in #6 seems to indicate it would be a big lift to get it working outside a vscode environment.

Has anyone looked into the options yet for working with Dart AST to/from disk?

**Comment by gmlewis** [comment]
Hmmm... that's a great question.  I have not thought about a stand-alone version yet.

Honestly, if I were to write a stand-alone tool, I would write it in Go.  :joy:

I'm a bit swamped with work at the moment, but I'll keep thinking about it. Maybe it wouldn't be too bad with Go. Thanks for the suggestion!

**Comment by gmlewis** [comment]
Hi @themightychris - I finally got some time to look into this, and wrote a Go stand-alone version of the `flutter-stylizer` that runs on Linux, Windows, and Mac.

It's available here: https://github.com/gmlewis/go-flutter-stylizer/

Please let me know if you have any problems with it.
Closing issue as resolved.

**Comment by themightychris** [comment]
awesome, thanks @gmlewis !
