### ISSUE TITLE
Add support for member overrides

### ISSUE THREAD

**Issue by BreSmit521** [gmlewis/flutter-stylizer#16]
**Is your feature request related to a problem? Please describe.**
Currently instance variables that are overrides are grouped with the "public-override-methods" ordering but it would be nice to allow these to be put with my other instance variables

**Describe the solution you'd like**
Add the ability to order something like "public-override-variables" separately from "public-override-methods" if possible

**Additional context**
Currently running this plugin on a file with overridden instance variables sorts like this :
```
class Chat extends Equatable implements SubscriptionObject {
  final String displayName;
  final ChatText? lastText;
  final List<User> users;

  Chat({
    required this.id,
    required this.users,
    required this.lastText,
    required this.displayName,
  });

  @override
  final String id;

  @override
  List<Object?> get props => [
        id,
        users,
        lastText,
        displayName,
      ];
}
```

The requested functionality would allow us to order as something like this :
```
@immutable
class Chat extends Equatable implements SubscriptionObject {
  @override
  final String id;
  final String displayName;
  final ChatText? lastText;
  final List<User> users;

  Chat({
    required this.id,
    required this.users,
    required this.lastText,
    required this.displayName,
  });


  @override
  List<Object?> get props => [
        id,
        users,
        lastText,
        displayName,
      ];
}
```

**Comment by gmlewis** [comment]
Thank you, @BreSmit521 for the suggestion.  I've gone ahead and implemented this in: https://github.com/gmlewis/flutter-stylizer/releases/tag/v0.0.17

Please check out the CHANGELOG.md or README.md as this caused a breaking change in the extension settings.
You will need to add a new field or the extension will use the built-in defaults.

Please let me know if you have any problems with the new feature.

**Comment by BreSmit521** [comment]
This is great and working exactly as expected!! Thank you so much for such a quick response!
