### ISSUE TITLE
Function-type variable is treated the same as function

### ISSUE THREAD

**Issue by maxpill** [gmlewis/flutter-stylizer#17]
Hello,

Flutter stylizer treats function-type variable such as

` final String Function() functionName;`

the same as a function

```
String fun(){
return "fun";
}
```

and instead it being among other final variables its sorted among functions.

v. 0.0.17

**Comment by gmlewis** [comment]
Thank you for the report, @maxpill !  I'll take a look.

**Comment by gmlewis** [comment]
@maxpill - this should be fixed in release: https://github.com/gmlewis/flutter-stylizer/releases/tag/v0.0.18

Please let me know if you find any other bugs, and thanks again for the report!

**Comment by maxpill** [comment]
Great!

Glad that you fixed it. So happy that I can use your tool in my daily work again :)
