### ISSUE TITLE
AutoSave Format

### ISSUE THREAD

**Issue by jscti** [gmlewis/flutter-stylizer#22]
Hi there, readme page states : 

> Without tooling to enforce a consistent style, developing code is less fun. Having an automated tool to do this ugly work for you, however, makes coding a lot more enjoyable, as you don't have to worry about the rules, _**but can just run the plugin on file save**_, and the rules are automatically enforced.

But how to enable this ?
I'm part of those guys that only use a formatting tool when it's automatically applied.

Thanks

**Comment by gmlewis** [comment]
I don't do this myself, and the plugin doesn't natively support format-on-save, but you could use another extension... possibly something like this:
https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave

**Comment by jscti** [comment]
Well ok .. just remove "but can just run the plugin on file save, and the rules are automatically enforced" then ;)

**Comment by gmlewis** [comment]
Thank you, @jscti - point taken, and I apologize for the confusion!

I've added this: https://github.com/gmlewis/flutter-stylizer/commit/6d1f95ab7fa78f3e533ff62c92ec365a269f3874
to hopefully address the confusion.

I don't think this warrants a separate plugin release, but at least it will be there for the next release (whenever that is).
